version: "3.7"

services:
  rabbitmq:
    container_name: rabbit-mq
    build: 
      dockerfile: DockerFile
      context: .
    image: rabbitmq:3.8.7
    ports:
      - "5672:5672"
      - "5671:5671"
      - "4369:4369"
      - "15672:15672"
      - "15671:15671"
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: curso-rabbit
      RABBITMQ_DEFAULT_PASS: curso-rabbit
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    networks:
      - curso-rabbit
networks:
  curso-rabbit:
