server:
  port: 8081
spring:
  rabbitmq:
    port: 5672
    username: curso-rabbit
    password: curso-rabbit
    request:
      exchange:
        producer: ex.producer.aula-spring
      routing-key:
        producer: rk.producer.aula-spring
      deadletter:
        producer: dl.producer.aula-spring